# Disabled cache in hope of improving reliability of AppVeyor builds
#cache:
#- "c:\\sr" # stack root, short paths == fewer problems

build: off

before_test:
# http://help.appveyor.com/discussions/problems/6312-curl-command-not-found
- IF "%BITS%" == "32" SET ARCH=i686
- IF "%BITS%" == "64" SET ARCH=x86_64
- SET PATH=C:\msys64\mingw%BITS%\bin;%PATH%;C:\msys64\usr\bin
- SET PATH=C:\Program Files\Git\mingw64\bin;%PATH%
- pacman --noconfirm -S mingw-w64-%ARCH%-gtk3
- curl -sS -ostack.zip -L --insecure http://www.stackage.org/stack/windows-%ARCH%
- 7z x stack.zip stack.exe

clone_folder: "c:\\stack"
environment:
  global:
    STACK_ROOT: "c:\\sr"

test_script:
- stack setup > nul
# The ugly echo "" hack is to avoid complaints about 0 being an invalid file
# descriptor
- echo "" | stack --no-terminal test --jobs 1
