# Disabled cache in hope of improving reliability of AppVeyor builds
#cache:
#- "c:\\sr" # stack root, short paths == fewer problems

build: off

environment:
  arch: x64
  global:
    STACK_ROOT: "c:\\sr" 

before_test:
# http://help.appveyor.com/discussions/problems/6312-curl-command-not-found
- SET PATH=C:\msys64\usr\bin;%PATH%
- pacman -Syu
- pacman -S --needed --noconfirm mingw-w64-x86_64-toolchain autoconf automake libtool make match mingw-w64-x86_64-libtool
- pacman --noconfirm -S mingw-w64-x86_64-gtk3 mingw-w64-x86_64-cairo mingw-w64-x86_64-gobject-introspection mingw-w64-glib2 mingw-w64-pango
- curl -sS -ostack.zip -L --insecure http://www.stackage.org/stack/windows-x86_64
- 7z x stack.zip stack.exe

clone_folder: "c:\\stack"

test_script:
- stack setup > nul
# The ugly echo "" hack is to avoid complaints about 0 being an invalid file
# descriptor
- echo "" | stack --no-terminal test --jobs 1
