name: hlabyrinth
version: '0.1.0.0'
category: Game
author: Kilian Kilger
maintainer: kkilger@gmail.com
license: GPL-3
extra-source-files:
- ChangeLog.md
other-extensions:
- MultiParamTypeClasses
- FlexibleInstances
- FunctionalDependencies
- DeriveGeneric
ghc-options:
- -rtsopts
dependencies:
- base >=4.10 && <4.11
- binary >= 0.8 && <0.9
- directory >=1.3 && <1.4
- filepath >=1.4 && <2
- optparse-applicative >=0.13.0 && <0.15
- gtk3 >=0.14.8 && <0.15
- cairo >=0.13.4 && <0.14
- pango >=0.13.4 && <0.14
- glib >=0.13.5 && <0.14
- text >=1.2.2.1 && <1.3
- mtl >=2.2.1 && <2.3
- array >=0.5.1 && <0.6
- stm >=2.4.4.1 && <2.5
- transformers >=0.5.2 && <0.6
- errors >=2.2.2 && <2.3
- mmorph >= 1.0.9 && <1.2
- search-algorithms >=0.3 && <0.4
executables:
  hlabyrinth:
    main: Main.hs
    source-dirs: src
    when: 
      - condition: flag(static)
        ld-options: 
        - -static
        - -pthread
      - condition: flag(llvm)
        ghc-options:
        - -fllvm
      - condition: flag(threaded)
        ghc-options:
        - -threaded 
      - condition: flag(optimize)
        ghc-options:
        - -O2
      - condition: flag(debug)
        ghc-options:
        - -debug
flags:
  static:
    description: Pass -static/-pthread to ghc when linking the stack binary.
    manual: true
    default: true
  llvm:
    description: Build with llvm backend
    manual: true
    default: true
  threaded: 
    description: Build with threaded ghc runtime
    manual: true
    default: true
  optimize:
    description: Build with optimizations enabled
    manual: true
    default: true
  debug:
    description: Use debug runtime for ghc
    manual: true
    default: false
