name: hlabyrinth
version: '0.2.0.1'
category: Game
author: Kilian Kilger
maintainer: kkilger@gmail.com
license: GPL-3
extra-source-files:
- ChangeLog.md
default-extensions: 
- MonoLocalBinds 
other-extensions:
- MultiParamTypeClasses
- FlexibleInstances
- FunctionalDependencies
- TemplateHaskell
ghc-options:
- -rtsopts
dependencies:
- base
- directory
- filepath
- optparse-applicative
- haskell-gi-base
- gi-gtk
- gi-pango 
- gi-cairo
- gi-glib
- gi-gdk
- gi-pangocairo
- gi-cairo-render
- gi-cairo-connector
- text
- mtl
- array
- stm
- transformers
- errors 
- mmorph 
- search-algorithms 
- pureMD5 
- bytestring
- cereal 
- safecopy 
- hxt-unicode
executables:
  hlabyrinth:
    main: Main.hs
    source-dirs: src
    when: 
      - condition: flag(llvm)
        ghc-options:
        - -fllvm
      - condition: flag(threaded)
        ghc-options:
        - -threaded 
      - condition: flag(optimize)
        ghc-options:
        - -O2
      - condition: flag(debug)
        ghc-options:
        - -debug
flags:
  llvm:
    description: Build with llvm backend
    manual: true
    default: false
  threaded: 
    description: Build with threaded ghc runtime
    manual: true
    default: true
  optimize:
    description: Build with optimizations enabled
    manual: true
    default: true
  debug:
    description: Use debug runtime for ghc
    manual: true
    default: false
