name: hlabyrinth
version: '0.1.0.0'
category: Game
author: Kilian Kilger
maintainer: kkilger@gmail.com
license: GPL-3
extra-source-files:
- ChangeLog.md
other-extensions:
- MultiParamTypeClasses
- FlexibleInstances
- FunctionalDependencies
ghc-options:
- -threaded
- -rtsopts
- -O2
dependencies:
- base >=4.9 && <4.10
- optparse-applicative >=0.13.0 && <0.15
- gtk3 >=0.14.8 && <0.15
- cairo >=0.13.4 && <0.14
- pango >=0.13.4 && <0.14
- glib >=0.13.5 && <0.14
- text >=1.2.2.1 && <1.3
- mtl >=2.2.1 && <2.3
- array >=0.5.1 && <0.6
- stm >=2.4.4.1 && <2.5
- transformers >=0.5.2 && <0.6
- errors >=2.2.2 && <2.3
- mmorph >= 1.0.9 && <1.2
executables:
  hlabyrinth:
    main: Main.hs
    source-dirs: src
