resolver: lts-14.16
packages:
  - gi-cairo-render
  - gi-cairo-connector
  - examples/sdl
  - examples/clock
  - examples/hlabyrinth
extra-deps:
  - gi-gdk-3.0.15
  - gi-gtk-3.0.22
  - gi-pango-1.0.16
  - gi-pangocairo-1.0.16
  - gi-gdkpixbuf-2.0.15 
  - gi-gio-2.0.18
