resolver: lts-16.13
packages:
  - gi-cairo-render
  - gi-cairo-connector
  - examples/sdl
  - examples/clock
  - examples/hlabyrinth
extra-deps:
  - gi-pangocairo-1.0.23@sha256:04dacf055fef4e19dd0276a8c2b5df08332877600b0014beecd2eaa764495ec6,3158
