flags: {}
packages:
- .
extra-deps:
- gi-gtk-3.0.22
- gi-pango-1.0.16
- gi-gdk-3.0.15
- gi-gdkpixbuf-2.0.15
- gi-gio-2.0.17
flags:
  gi-gdk:
    enable-overloading: false
  gi-gdkpixbuf:
    enable-overloading: false
  gi-gio:
    enable-overloading: false
  gi-gtk:
    enable-overloading: false
  gi-pango:
    enable-overloading: false
resolver: lts-11.3
